blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/<int:id>/', views.Edit, name='edit'),
    path('delete/<int:id>/', views.Delete, name='delete'),
    path('addpost/', views.addpost, name='addpost'),
]

blog_project/blog/models.py
from django.db import models

# Create your models here.
class  post(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()

blog_project/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import post


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='confirm_password(again)',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name',
                  'last_name': 'Last Name', 'email': 'Email'}
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'})
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'autofocus': True}))
    password = forms.CharField(label="Password", strip=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))


class postform(forms.ModelForm):
    class Meta:
        model = post
        fields = ['title', 'desc']
        labels = {'title': 'Title', 'desc': 'Description'}
        widgets = {'title': forms.TextInput(
            attrs={'class': 'form-control'}), 'desc': forms.Textarea(attrs={'class': 'form-control'})}

blog_project/blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
# Create your views here.
from .forms import SignUpForm, LoginForm, postform
from django.contrib.auth import authenticate, login, logout
from .models import post
from django.contrib.auth.models import Group
from django.core.cache import cache


def home(request):
    posts = post.objects.all()
    return render(request, 'blog/home.html', {'posts': posts})


def about(request):
    return render(request, 'blog/about.html')


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request.POST, data=request.POST)
            if(form.is_valid()):
                uname = form.cleaned_data['username']
                passw = form.cleaned_data['password']
                user = authenticate(username=uname, password=passw)
                if(user is not None):
                    login(request, user)
                    messages.success(
                        request, 'congratulations You have successfully loged in')
                    return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginForm()
        return render(request, 'blog/login.html', {'form': form})
    else:
        return HttpResponseRedirect('/dashboard/')


def contact(request):
    if request.user.is_authenticated:
        return render(request, 'blog/contact.html')
    else:
        return HttpResponseRedirect('/login/')


def dashboard(request):
    if request.user.is_authenticated:
        posts = post.objects.all()
        user = request.user
        full_name = user.get_full_name()
        gps = user.groups.all()
        ct = cache.get('count',version = user.pk)
        ip = request.session.get('ip',0)
        return render(request, 'blog/dashboard.html', {'ct': ct, 'ip':ip, 'posts': posts, 'full_name': full_name, 'groups': gps})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if(form.is_valid()):
            messages.success(
                request, 'congratulations You have successfully loged in')
            user = form.save()
            group = Group.objects.get(name='author')
            user.groups.add(group)
            return HttpResponseRedirect('/login/')
    else:
        form = SignUpForm()
    return render(request, 'blog/signup.html', {'form': form})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def addpost(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = postform(request.POST)
            if fm.is_valid():
                title = fm.cleaned_data['title']
                desc = fm.cleaned_data['desc']
                pst = post(title=title, desc=desc)
                pst.save()
        else:
            fm = postform()
        return render(request, 'blog/addpost.html', {'form': fm})
    else:
        return HttpResponseRedirect('/login/')


def Edit(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            eo = post.objects.get(pk=id)
            fm = postform(request.POST, instance=eo)
            if fm.is_valid():
                fm.save()
        else:
            eo = post.objects.get(pk=id)
            fm = postform(instance=eo)
        return render(request, 'blog/updatepost.html', {'form': fm, 'ob': eo})
    else:
        return HttpResponseRedirect('/login/')


def Delete(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            do = post.objects.get(pk=id)
            do.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

blog_project/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>this is about html</h1>
  </body>
</html>

blog_project/blog/templates/blog/addpost.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}


<div class="col-sm-10">
  <h3 class="text-white my-5">Dashboard/ Addpost</h3>
</div>
<form action="" method="post" class="form-group">
  {% csrf_token %}
   {% for fm in form %}
      <div class="form-group">
        {{fm.label_tag}} {{fm}} {{ fm.errors | striptags }}
      </div>
      {% endfor %}
  <input type="submit" value="Add" class="btn btn-success" />
  <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
</form>
{% endblock %}

blog_project/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
  </head>
  <body>
    <div clas="container-fluid bg dark">{% include 'blog/navbar.html' %}</div>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">{% block msg %} {% endblock msg %}</div>
      </div>
      <div class="row">
        {% block side %} {% endblock side %} {% block content %} {% endblock content %}
      </div>
    </div>

    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="{% static 'blog/js/jquery.js' %}"></script>
    <script src="{% static 'blog/js/popper.js' %}"></script>
  </body>
</html>

blog_project/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>contact</h1>
  </body>
</html>

blog_project/blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %} {% load static %} {% block msg %} {% if messages %} {% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span class="area-hidden">&times;</span>
  </button>
</div>
{% endfor %} {% endif %} {% endblock %}

{% block side %}
<div class="pull-right col-sm-2 text-white my-5 text-center">
  <h4 class="my-5">Profile</h4>
  <h5>welcome {{full_name}} </h5>
 {% for group in groups %}
  <p>{{group.name}}</p>
  {% endfor %}
  <h5>ip:{{ip}}</h5>
  <button type="button" class="btn btn-danger mt-3">
    Login times: <span class="badge badge-light">{{ct}}</span>
  </button>
</div>
{% endblock side %}
 
{% block content %}

<div class="row">
  <div class="col-sm-12">
    <h2 class="text-center alert alert-info">My blogs</h2>
    <a href="{% url 'addpost' %}" value="Edit" class="btn btn-warning btn-sm">Add New Blog
    </a>
    {% if posts %}
    <table class="table table-hover alert alert-light">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          {% for post in posts %}
          <th scope="row">{{post.id}}</th>
          <td>{{post.title}}</td>
          <td>{{post.desc}}</td>
          <td>
            
            <a href="{% url 'edit' post.id %}" value="Edit" class="btn btn-warning btn-sm">Edit</a>
            {% if perms.blog.delete_post %}
            <form action="{% url 'delete' post.id %}" method="POST" class="d-inline">
              {% csrf_token %}
              <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
            </form>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% endif %}
  </div>
</div>
{% endblock content %} 

blog_project/blog/templates/blog/home.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}
<div class="col-sm-8">
  <h3>HOME PAGE</h3>

  {% for post in posts%}
  <div class="jumbotron jumbotron-fluid jumbo-color">
    <div class="container">
      <h1 class="display-4">{{post.title}}</h1>
      <p class="lead">{{post.desc}}</p>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

blog_project/blog/templates/blog/login.html
{% extends 'blog/base.html' %} 
    {% block msg %} {% if messages %} {% for message in messages %}
    <div
      {%
      if
      message.tags
      %}
      class="alert alert-{{message.tags}} alert-dismissible fade show"
      {%
      endif
      %}
    >
      <strong>{{message}}</strong>
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span class="area-hidden">&times;</span>
      </button>
    </div>
    {% endfor %} {% endif %} {% endblock msg %}
    
 {% block content %}
    
    <h3> Log In form </h3>
    <form action="{% url 'login' %}" method="post" novalidate>
      {% csrf_token %} 
      {% for fm in form %}
      <div class="form-group">
        {{fm.label_tag}} {{fm}} {{ fm.errors | striptags }}<br />
      </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary" value="submit" />

      {% if form.non_field_errors %} {% for errors in form.non_field_errors %}
      <p class="alert alert-danger my-3">{{error}}</p>
      {% endfor %} {% endif %}
    </form>

{% endblock %}

blog_project/blog/templates/blog/logout.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
     {% block
msg %} {% if messages %} {% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span class="area-hidden">&times;</span>
  </button>
</div>
{% endfor %} {% endif %} {% endblock msg %}
    <h1>logout</h1>
  </body>
</html>

blog_project/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mini BLock</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}">Dashborad</a>
        </li>
        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">SignUp</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

blog_project/blog/templates/blog/signup.html
{% extends 'blog/base.html' %} 
     {% block msg %} {% if messages %} {% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span class="area-hidden">&times;</span>
  </button>
</div>
{% endfor %} {% endif %} {% endblock msg %}

  {% block content %}
    <h3>Sign up from</h3>
    <form action="{% url 'signup' %}" method="post" novalidate>
      {% csrf_token %} {% for fm in form %}
      <div class="form-group">
        {{fm.label_tag}} {{fm}} {{ fm.errors | striptags }}<br />
      </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary" value="submit" />

      {% if form.non_field_errors %} {% for errors in form.non_field_errors %}
      <p class="alert alert-danger my-3">{{error}}</p>
      {% endfor %} {% endif %}
    </form>
{% endblock %}

blog_project/blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10">
     <h3 class="text-white my-5">Dashboard/ Addpost</h3>
 <form action="{% url 'edit' ob.id  %}" method="post" class="form-group">
  {% csrf_token %}
  <table>
   {% for fm in form %}
      <div class="form-group">
          <tr height='5px'>
              <td>
        {{fm.label_tag}} {{fm}} {{ fm.errors | striptags }}<br />
        </td>
          </tr>
      </div>
      {% endfor %}
      <tr>
          <td>
  <input type="submit" value="Update" class="btn btn-success" />
  <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
</td>
  </tr>
</form>
</table>
 </div>
{% endblock %}